package com.xignite.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-09-12T20:24:58.094+03:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://www.xignite.com/services/", name = "XigniteCurrenciesSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface XigniteCurrenciesSoap {

    /**
     * This operation returns a complete range of stock quotes for a currency pair.
     *             
     */
    @WebMethod(operationName = "GetHistoricalMonthlyCrossRatesRange", action = "http://www.xignite.com/services/GetHistoricalMonthlyCrossRatesRange")
    @RequestWrapper(localName = "GetHistoricalMonthlyCrossRatesRange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMonthlyCrossRatesRange")
    @ResponseWrapper(localName = "GetHistoricalMonthlyCrossRatesRangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalMonthlyCrossRatesRangeResponse")
    @WebResult(name = "GetHistoricalMonthlyCrossRatesRangeResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.FullHistoricalCrossRates getHistoricalMonthlyCrossRatesRange(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * Draw a historical currency chart for a date range.
     */
    @WebMethod(operationName = "GetCurrencyChart", action = "http://www.xignite.com/services/GetCurrencyChart")
    @RequestWrapper(localName = "GetCurrencyChart", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChart")
    @ResponseWrapper(localName = "GetCurrencyChartResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartResponse")
    @WebResult(name = "GetCurrencyChartResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HistoricalChart getCurrencyChart(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Preset", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String preset
    );

    /**
     * This operation returns a range of cross-rates for a currency pair.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesAsOf", action = "http://www.xignite.com/services/GetHistoricalCrossRatesAsOf")
    @RequestWrapper(localName = "GetHistoricalCrossRatesAsOf", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesAsOf")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesAsOfResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesAsOfResponse")
    @WebResult(name = "GetHistoricalCrossRatesAsOfResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HistoricalCrossRates getHistoricalCrossRatesAsOf(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.PeriodTypes periodType,
        @WebParam(name = "Periods", targetNamespace = "http://www.xignite.com/services/")
        int periods
    );

    /**
     * Draw a intraday currency chart for a time range
     */
    @WebMethod(operationName = "GetCurrencyIntradayChart", action = "http://www.xignite.com/services/GetCurrencyIntradayChart")
    @RequestWrapper(localName = "GetCurrencyIntradayChart", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChart")
    @ResponseWrapper(localName = "GetCurrencyIntradayChartResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartResponse")
    @WebResult(name = "GetCurrencyIntradayChartResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CurrencyChartIntraday getCurrencyIntradayChart(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endTime,
        @WebParam(name = "TimeZone", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String timeZone,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String periodType,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods,
        @WebParam(name = "Preset", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String preset
    );

    /**
     * Convert value from one currency to another in real-time.
     *             
     */
    @WebMethod(operationName = "ConvertRealTimeValue", action = "http://www.xignite.com/services/ConvertRealTimeValue")
    @RequestWrapper(localName = "ConvertRealTimeValue", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertRealTimeValue")
    @ResponseWrapper(localName = "ConvertRealTimeValueResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertRealTimeValueResponse")
    @WebResult(name = "ConvertRealTimeValueResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ExchangeConversion convertRealTimeValue(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String to,
        @WebParam(name = "Amount", targetNamespace = "http://www.xignite.com/services/")
        double amount
    );

    /**
     * Returns all valid cross rates for a currency.
     */
    @WebMethod(operationName = "GetAllCrossRatesForACurrency", action = "http://www.xignite.com/services/GetAllCrossRatesForACurrency")
    @RequestWrapper(localName = "GetAllCrossRatesForACurrency", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllCrossRatesForACurrency")
    @ResponseWrapper(localName = "GetAllCrossRatesForACurrencyResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAllCrossRatesForACurrencyResponse")
    @WebResult(name = "GetAllCrossRatesForACurrencyResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRateTableLineWithBidAsk getAllCrossRatesForACurrency(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol
    );

    /**
     * Returns historical currency cross-rate tables for a range of dates.
     *             
     */
    @WebMethod(operationName = "GetCurrencyReport", action = "http://www.xignite.com/services/GetCurrencyReport")
    @RequestWrapper(localName = "GetCurrencyReport", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyReport")
    @ResponseWrapper(localName = "GetCurrencyReportResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyReportResponse")
    @WebResult(name = "GetCurrencyReportResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.Report getCurrencyReport(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String to,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * Returns an official cross-rate as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetOfficialCrossRates", action = "http://www.xignite.com/services/GetOfficialCrossRates")
    @RequestWrapper(localName = "GetOfficialCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRates")
    @ResponseWrapper(localName = "GetOfficialCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRatesResponse")
    @WebResult(name = "GetOfficialCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfHistoricalCrossRate getOfficialCrossRates(

        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.CountryTypes countryType,
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Returns a real-time currency cross-rate.
     */
    @WebMethod(operationName = "GetRealTimeCrossRate", action = "http://www.xignite.com/services/GetRealTimeCrossRate")
    @RequestWrapper(localName = "GetRealTimeCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRate")
    @ResponseWrapper(localName = "GetRealTimeCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateResponse")
    @WebResult(name = "GetRealTimeCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRate getRealTimeCrossRate(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies to
    );

    /**
     * Returns the latest possible cross rate.
     */
    @WebMethod(operationName = "GetLatestCrossRate", action = "http://www.xignite.com/services/GetLatestCrossRate")
    @RequestWrapper(localName = "GetLatestCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRate")
    @ResponseWrapper(localName = "GetLatestCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRateResponse")
    @WebResult(name = "GetLatestCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRate getLatestCrossRate(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String to
    );

    /**
     * Returns an official cross-rate as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetOfficialCrossRateBidAsk", action = "http://www.xignite.com/services/GetOfficialCrossRateBidAsk")
    @RequestWrapper(localName = "GetOfficialCrossRateBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRateBidAsk")
    @ResponseWrapper(localName = "GetOfficialCrossRateBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRateBidAskResponse")
    @WebResult(name = "GetOfficialCrossRateBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.FullHistoricalCrossRate getOfficialCrossRateBidAsk(

        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.CountryTypes countryType,
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Returns multiple cross-rates as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetMutipleHistoricalCrossRates", action = "http://www.xignite.com/services/GetMutipleHistoricalCrossRates")
    @RequestWrapper(localName = "GetMutipleHistoricalCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetMutipleHistoricalCrossRates")
    @ResponseWrapper(localName = "GetMutipleHistoricalCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetMutipleHistoricalCrossRatesResponse")
    @WebResult(name = "GetMutipleHistoricalCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.MultipleHistoricalCrossRates getMutipleHistoricalCrossRates(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Returns the default design class for the currency Chart.
     *             
     */
    @WebMethod(operationName = "GetChartDesign", action = "http://www.xignite.com/services/GetChartDesign")
    @RequestWrapper(localName = "GetChartDesign", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetChartDesign")
    @ResponseWrapper(localName = "GetChartDesignResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetChartDesignResponse")
    @WebResult(name = "GetChartDesignResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ChartDesign getChartDesign()
;

    /**
     * Draw a intraday currency chart for a time range in a binary format
     *             
     */
    @WebMethod(operationName = "GetCurrencyIntradayChartCustomBinary", action = "http://www.xignite.com/services/GetCurrencyIntradayChartCustomBinary")
    @RequestWrapper(localName = "GetCurrencyIntradayChartCustomBinary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustomBinary")
    @ResponseWrapper(localName = "GetCurrencyIntradayChartCustomBinaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustomBinaryResponse")
    @WebResult(name = "GetCurrencyIntradayChartCustomBinaryResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ChartBinary getCurrencyIntradayChartCustomBinary(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endTime,
        @WebParam(name = "TimeZone", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String timeZone,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String periodType,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.ChartDesign design
    );

    /**
     * Convert value from one currency to another as of a historical date.
     *             
     */
    @WebMethod(operationName = "ConvertHistoricalValue", action = "http://www.xignite.com/services/ConvertHistoricalValue")
    @RequestWrapper(localName = "ConvertHistoricalValue", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertHistoricalValue")
    @ResponseWrapper(localName = "ConvertHistoricalValueResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ConvertHistoricalValueResponse")
    @WebResult(name = "ConvertHistoricalValueResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ExchangeConversion convertHistoricalValue(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String to,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate,
        @WebParam(name = "Amount", targetNamespace = "http://www.xignite.com/services/")
        double amount
    );

    /**
     * List supported official rates.
     */
    @WebMethod(operationName = "ListOfficialRates", action = "http://www.xignite.com/services/ListOfficialRates")
    @RequestWrapper(localName = "ListOfficialRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListOfficialRates")
    @ResponseWrapper(localName = "ListOfficialRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListOfficialRatesResponse")
    @WebResult(name = "ListOfficialRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.OfficialRates listOfficialRates()
;

    /**
     * Returns the high and the low ticks for a historical time range.
     *             
     */
    @WebMethod(operationName = "GetHistoricalHighLow", action = "http://www.xignite.com/services/GetHistoricalHighLow")
    @RequestWrapper(localName = "GetHistoricalHighLow", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalHighLow")
    @ResponseWrapper(localName = "GetHistoricalHighLowResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalHighLowResponse")
    @WebResult(name = "GetHistoricalHighLowResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HighLowTick getHistoricalHighLow(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartDateTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDateTime
    );

    /**
     * Returns a historical currency cross-rate table.
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTable", action = "http://www.xignite.com/services/GetHistoricalCrossRateTable")
    @RequestWrapper(localName = "GetHistoricalCrossRateTable", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTable")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTableResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableResponse")
    @WebResult(name = "GetHistoricalCrossRateTableResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRateTable getHistoricalCrossRateTable(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Returns a cross-rate as of a historical date.
     */
    @WebMethod(operationName = "GetHistoricalCrossRate", action = "http://www.xignite.com/services/GetHistoricalCrossRate")
    @RequestWrapper(localName = "GetHistoricalCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRate")
    @ResponseWrapper(localName = "GetHistoricalCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateResponse")
    @WebResult(name = "GetHistoricalCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HistoricalCrossRate getHistoricalCrossRate(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Returns a real-time currency cross-rate.
     */
    @WebMethod(operationName = "GetRawCrossRates", action = "http://www.xignite.com/services/GetRawCrossRates")
    @RequestWrapper(localName = "GetRawCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRates")
    @ResponseWrapper(localName = "GetRawCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRatesResponse")
    @WebResult(name = "GetRawCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfCrossRate getRawCrossRates(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols
    );

    /**
     * Returns a historical currency cross-rate table.
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTableBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRateTableBidAsk")
    @RequestWrapper(localName = "GetHistoricalCrossRateTableBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTableBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableBidAskResponse")
    @WebResult(name = "GetHistoricalCrossRateTableBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRateTableWithBidAsk getHistoricalCrossRateTableBidAsk(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * List supported currencies.
     */
    @WebMethod(operationName = "ListCurrencies", action = "http://www.xignite.com/services/ListCurrencies")
    @RequestWrapper(localName = "ListCurrencies", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListCurrencies")
    @ResponseWrapper(localName = "ListCurrenciesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListCurrenciesResponse")
    @WebResult(name = "ListCurrenciesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CurrencyList listCurrencies()
;

    /**
     * Returns the high and the low ticks for today.
     */
    @WebMethod(operationName = "GetIntradayHighLow", action = "http://www.xignite.com/services/GetIntradayHighLow")
    @RequestWrapper(localName = "GetIntradayHighLow", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIntradayHighLow")
    @ResponseWrapper(localName = "GetIntradayHighLowResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetIntradayHighLowResponse")
    @WebResult(name = "GetIntradayHighLowResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HighLowTick getIntradayHighLow(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartDateTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDateTime
    );

    /**
     * Returns a set of real-time currency forward rates.
     */
    @WebMethod(operationName = "GetRealTimeForwardRate", action = "http://www.xignite.com/services/GetRealTimeForwardRate")
    @RequestWrapper(localName = "GetRealTimeForwardRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeForwardRate")
    @ResponseWrapper(localName = "GetRealTimeForwardRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeForwardRateResponse")
    @WebResult(name = "GetRealTimeForwardRateResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ForwardRate getRealTimeForwardRate(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String to
    );

    /**
     * Returns multiple cross-rates as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRates", action = "http://www.xignite.com/services/GetHistoricalCrossRates")
    @RequestWrapper(localName = "GetHistoricalCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRates")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesResponse")
    @WebResult(name = "GetHistoricalCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfHistoricalCrossRate getHistoricalCrossRates(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Returns a real-time currency cross-rate table.
     */
    @WebMethod(operationName = "GetRealTimeCrossRateTableWithBidAsk", action = "http://www.xignite.com/services/GetRealTimeCrossRateTableWithBidAsk")
    @RequestWrapper(localName = "GetRealTimeCrossRateTableWithBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableWithBidAsk")
    @ResponseWrapper(localName = "GetRealTimeCrossRateTableWithBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableWithBidAskResponse")
    @WebResult(name = "GetRealTimeCrossRateTableWithBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRateTableWithBidAsk getRealTimeCrossRateTableWithBidAsk(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols
    );

    /**
     * Draw a custom currency chart for a date range.
     */
    @WebMethod(operationName = "GetCurrencyChartCustomBinary", action = "http://www.xignite.com/services/GetCurrencyChartCustomBinary")
    @RequestWrapper(localName = "GetCurrencyChartCustomBinary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustomBinary")
    @ResponseWrapper(localName = "GetCurrencyChartCustomBinaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustomBinaryResponse")
    @WebResult(name = "GetCurrencyChartCustomBinaryResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ChartBinary getCurrencyChartCustomBinary(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.ChartDesign design
    );

    /**
     * Returns historical currency cross-rate tables for a range of dates.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTablesBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRateTablesBidAsk")
    @RequestWrapper(localName = "GetHistoricalCrossRateTablesBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTablesBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTablesBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTablesBidAskResponse")
    @WebResult(name = "GetHistoricalCrossRateTablesBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfCrossRateTableWithBidAsk getHistoricalCrossRateTablesBidAsk(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * Returns a range of ticks for a currency pair.
     */
    @WebMethod(operationName = "GetHistoricalTicks", action = "http://www.xignite.com/services/GetHistoricalTicks")
    @RequestWrapper(localName = "GetHistoricalTicks", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalTicks")
    @ResponseWrapper(localName = "GetHistoricalTicksResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalTicksResponse")
    @WebResult(name = "GetHistoricalTicksResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.Ticks getHistoricalTicks(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endTime,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate,
        @WebParam(name = "TickPrecision", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.TickPeriod tickPrecision,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods
    );

    /**
     * Returns a cross-rate with bid/ask as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRateBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRateBidAsk")
    @RequestWrapper(localName = "GetHistoricalCrossRateBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRateBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateBidAskResponse")
    @WebResult(name = "GetHistoricalCrossRateBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.FullHistoricalCrossRate getHistoricalCrossRateBidAsk(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Get Unit Of Account.
     */
    @WebMethod(operationName = "GetUnitOfAccount", action = "http://www.xignite.com/services/GetUnitOfAccount")
    @RequestWrapper(localName = "GetUnitOfAccount", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetUnitOfAccount")
    @ResponseWrapper(localName = "GetUnitOfAccountResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetUnitOfAccountResponse")
    @WebResult(name = "GetUnitOfAccountResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.UnitOfAccount getUnitOfAccount(

        @WebParam(name = "Currency", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String currency,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Returns a tick for a currency pair as of a specific time in the day.
     *             
     */
    @WebMethod(operationName = "GetTick", action = "http://www.xignite.com/services/GetTick")
    @RequestWrapper(localName = "GetTick", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTick")
    @ResponseWrapper(localName = "GetTickResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTickResponse")
    @WebResult(name = "GetTickResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.SingleTick getTick(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "Time", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String time
    );

    /**
     * This operation returns a range of cross-rates for a currency pair.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesBidAskAsOf", action = "http://www.xignite.com/services/GetHistoricalCrossRatesBidAskAsOf")
    @RequestWrapper(localName = "GetHistoricalCrossRatesBidAskAsOf", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskAsOf")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesBidAskAsOfResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskAsOfResponse")
    @WebResult(name = "GetHistoricalCrossRatesBidAskAsOfResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.FullHistoricalCrossRates getHistoricalCrossRatesBidAskAsOf(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.PeriodTypes periodType,
        @WebParam(name = "Periods", targetNamespace = "http://www.xignite.com/services/")
        int periods
    );

    /**
     * This operation returns an array average daily historical cross-rates for a period.
     *             
     */
    @WebMethod(operationName = "GetAverageHistoricalCrossRates", action = "http://www.xignite.com/services/GetAverageHistoricalCrossRates")
    @RequestWrapper(localName = "GetAverageHistoricalCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRates")
    @ResponseWrapper(localName = "GetAverageHistoricalCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRatesResponse")
    @WebResult(name = "GetAverageHistoricalCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfAverageHistoricalCrossRate getAverageHistoricalCrossRates(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * Returns a real-time currency cross-rate table as an HTML Output.
     *             
     */
    @WebMethod(operationName = "GetSimpleRealTimeCrossRateTableAsHTML", action = "http://www.xignite.com/services/GetSimpleRealTimeCrossRateTableAsHTML")
    @RequestWrapper(localName = "GetSimpleRealTimeCrossRateTableAsHTML", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSimpleRealTimeCrossRateTableAsHTML")
    @ResponseWrapper(localName = "GetSimpleRealTimeCrossRateTableAsHTMLResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetSimpleRealTimeCrossRateTableAsHTMLResponse")
    @WebResult(name = "GetSimpleRealTimeCrossRateTableAsHTMLResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HTMLCrossRateTable getSimpleRealTimeCrossRateTableAsHTML(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "ColumnHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String columnHeaderStyle,
        @WebParam(name = "LineHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String lineHeaderStyle,
        @WebParam(name = "CellStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String cellStyle
    );

    /**
     * Returns a real-time currency cross-rate with the times in GMT.
     *             
     */
    @WebMethod(operationName = "GetRealTimeCrossRateGMT", action = "http://www.xignite.com/services/GetRealTimeCrossRateGMT")
    @RequestWrapper(localName = "GetRealTimeCrossRateGMT", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateGMT")
    @ResponseWrapper(localName = "GetRealTimeCrossRateGMTResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateGMTResponse")
    @WebResult(name = "GetRealTimeCrossRateGMTResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRate getRealTimeCrossRateGMT(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies to
    );

    /**
     * Returns the latest possible cross rate.
     */
    @WebMethod(operationName = "GetRealTimeCrossRates", action = "http://www.xignite.com/services/GetRealTimeCrossRates")
    @RequestWrapper(localName = "GetRealTimeCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRates")
    @ResponseWrapper(localName = "GetRealTimeCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRatesResponse")
    @WebResult(name = "GetRealTimeCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfCrossRate getRealTimeCrossRates(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols
    );

    /**
     * Returns historical currency cross-rate tables for a range of dates.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTables", action = "http://www.xignite.com/services/GetHistoricalCrossRateTables")
    @RequestWrapper(localName = "GetHistoricalCrossRateTables", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTables")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTablesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTablesResponse")
    @WebResult(name = "GetHistoricalCrossRateTablesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfCrossRateTable getHistoricalCrossRateTables(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * This operation returns the changes in a cross-rates over the last 6 months.
     *             
     */
    @WebMethod(operationName = "GetCrossRateChange", action = "http://www.xignite.com/services/GetCrossRateChange")
    @RequestWrapper(localName = "GetCrossRateChange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCrossRateChange")
    @ResponseWrapper(localName = "GetCrossRateChangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCrossRateChangeResponse")
    @WebResult(name = "GetCrossRateChangeResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRateChange getCrossRateChange(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol
    );

    /**
     * Returns a real-time currency cross-rate table.
     */
    @WebMethod(operationName = "GetRealTimeCrossRateTable", action = "http://www.xignite.com/services/GetRealTimeCrossRateTable")
    @RequestWrapper(localName = "GetRealTimeCrossRateTable", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTable")
    @ResponseWrapper(localName = "GetRealTimeCrossRateTableResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableResponse")
    @WebResult(name = "GetRealTimeCrossRateTableResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRateTable getRealTimeCrossRateTable(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols
    );

    /**
     * Returns an official cross-rate as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetOfficialCrossRatesBidAsk", action = "http://www.xignite.com/services/GetOfficialCrossRatesBidAsk")
    @RequestWrapper(localName = "GetOfficialCrossRatesBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRatesBidAsk")
    @ResponseWrapper(localName = "GetOfficialCrossRatesBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRatesBidAskResponse")
    @WebResult(name = "GetOfficialCrossRatesBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfFullHistoricalCrossRate getOfficialCrossRatesBidAsk(

        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.CountryTypes countryType,
        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * Draw a custom currency chart for a date range.
     */
    @WebMethod(operationName = "GetCurrencyChartCustom", action = "http://www.xignite.com/services/GetCurrencyChartCustom")
    @RequestWrapper(localName = "GetCurrencyChartCustom", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustom")
    @ResponseWrapper(localName = "GetCurrencyChartCustomResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartCustomResponse")
    @WebResult(name = "GetCurrencyChartCustomResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HistoricalChart getCurrencyChartCustom(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.ChartDesign design
    );

    /**
     * Returns a historical currency cross-rate table as an HTML Output.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRateTableAsHTML", action = "http://www.xignite.com/services/GetHistoricalCrossRateTableAsHTML")
    @RequestWrapper(localName = "GetHistoricalCrossRateTableAsHTML", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableAsHTML")
    @ResponseWrapper(localName = "GetHistoricalCrossRateTableAsHTMLResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRateTableAsHTMLResponse")
    @WebResult(name = "GetHistoricalCrossRateTableAsHTMLResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HTMLCrossRateTable getHistoricalCrossRateTableAsHTML(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate,
        @WebParam(name = "ColumnHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String columnHeaderStyle,
        @WebParam(name = "LineHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String lineHeaderStyle,
        @WebParam(name = "CellStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String cellStyle
    );

    /**
     * Returns a real-time currency cross-rate table as an HTML Output.
     *             
     */
    @WebMethod(operationName = "GetRealTimeCrossRateTableAsHTML", action = "http://www.xignite.com/services/GetRealTimeCrossRateTableAsHTML")
    @RequestWrapper(localName = "GetRealTimeCrossRateTableAsHTML", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableAsHTML")
    @ResponseWrapper(localName = "GetRealTimeCrossRateTableAsHTMLResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateTableAsHTMLResponse")
    @WebResult(name = "GetRealTimeCrossRateTableAsHTMLResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HTMLCrossRateTable getRealTimeCrossRateTableAsHTML(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "ColumnHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String columnHeaderStyle,
        @WebParam(name = "LineHeaderStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String lineHeaderStyle,
        @WebParam(name = "CellStyle", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String cellStyle
    );

    /**
     * Returns multiple cross-rates with bid/ask as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesBidAsk", action = "http://www.xignite.com/services/GetHistoricalCrossRatesBidAsk")
    @RequestWrapper(localName = "GetHistoricalCrossRatesBidAsk", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAsk")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesBidAskResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskResponse")
    @WebResult(name = "GetHistoricalCrossRatesBidAskResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfFullHistoricalCrossRate getHistoricalCrossRatesBidAsk(

        @WebParam(name = "Symbols", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbols,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * This operation returns a range of cross-rates for a currency pair.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesRange", action = "http://www.xignite.com/services/GetHistoricalCrossRatesRange")
    @RequestWrapper(localName = "GetHistoricalCrossRatesRange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesRange")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesRangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesRangeResponse")
    @WebResult(name = "GetHistoricalCrossRatesRangeResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HistoricalCrossRates getHistoricalCrossRatesRange(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * This operation returns an average daily historical cross-rates for a period.
     *             
     */
    @WebMethod(operationName = "GetAverageHistoricalCrossRate", action = "http://www.xignite.com/services/GetAverageHistoricalCrossRate")
    @RequestWrapper(localName = "GetAverageHistoricalCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRate")
    @ResponseWrapper(localName = "GetAverageHistoricalCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetAverageHistoricalCrossRateResponse")
    @WebResult(name = "GetAverageHistoricalCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.AverageHistoricalCrossRate getAverageHistoricalCrossRate(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * Draw a historical currency chart for a date range in binary format.
     *             
     */
    @WebMethod(operationName = "GetCurrencyChartBinary", action = "http://www.xignite.com/services/GetCurrencyChartBinary")
    @RequestWrapper(localName = "GetCurrencyChartBinary", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartBinary")
    @ResponseWrapper(localName = "GetCurrencyChartBinaryResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyChartBinaryResponse")
    @WebResult(name = "GetCurrencyChartBinaryResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ChartBinary getCurrencyChartBinary(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.HistoricalPeriodTypes periodType,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "Preset", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String preset
    );

    /**
     * Returns a range of ticks for a currency pair.
     */
    @WebMethod(operationName = "GetTicks", action = "http://www.xignite.com/services/GetTicks")
    @RequestWrapper(localName = "GetTicks", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTicks")
    @ResponseWrapper(localName = "GetTicksResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetTicksResponse")
    @WebResult(name = "GetTicksResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.Ticks getTicks(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endTime,
        @WebParam(name = "TickPrecision", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.TickPeriod tickPrecision,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods
    );

    /**
     * Returns a real-time currency cross-rate.
     */
    @WebMethod(operationName = "GetRawCrossRate", action = "http://www.xignite.com/services/GetRawCrossRate")
    @RequestWrapper(localName = "GetRawCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRate")
    @ResponseWrapper(localName = "GetRawCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRawCrossRateResponse")
    @WebResult(name = "GetRawCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRate getRawCrossRate(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies to
    );

    /**
     * This operation returns a range of cross-rates for a currency pair.
     *             
     */
    @WebMethod(operationName = "GetHistoricalCrossRatesBidAskRange", action = "http://www.xignite.com/services/GetHistoricalCrossRatesBidAskRange")
    @RequestWrapper(localName = "GetHistoricalCrossRatesBidAskRange", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskRange")
    @ResponseWrapper(localName = "GetHistoricalCrossRatesBidAskRangeResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetHistoricalCrossRatesBidAskRangeResponse")
    @WebResult(name = "GetHistoricalCrossRatesBidAskRangeResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.FullHistoricalCrossRates getHistoricalCrossRatesBidAskRange(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endDate
    );

    /**
     * Returns an official cross-rate as of a historical date.
     *             
     */
    @WebMethod(operationName = "GetOfficialCrossRate", action = "http://www.xignite.com/services/GetOfficialCrossRate")
    @RequestWrapper(localName = "GetOfficialCrossRate", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRate")
    @ResponseWrapper(localName = "GetOfficialCrossRateResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetOfficialCrossRateResponse")
    @WebResult(name = "GetOfficialCrossRateResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.HistoricalCrossRate getOfficialCrossRate(

        @WebParam(name = "CountryType", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.CountryTypes countryType,
        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.Currencies symbol,
        @WebParam(name = "AsOfDate", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String asOfDate
    );

    /**
     * List supported currencies.
     */
    @WebMethod(operationName = "ListActiveCurrencies", action = "http://www.xignite.com/services/ListActiveCurrencies")
    @RequestWrapper(localName = "ListActiveCurrencies", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListActiveCurrencies")
    @ResponseWrapper(localName = "ListActiveCurrenciesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.ListActiveCurrenciesResponse")
    @WebResult(name = "ListActiveCurrenciesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CurrencyList listActiveCurrencies()
;

    /**
     * Returns a real-time currency cross-rate.
     */
    @WebMethod(operationName = "GetRealTimeCrossRateAsString", action = "http://www.xignite.com/services/GetRealTimeCrossRateAsString")
    @RequestWrapper(localName = "GetRealTimeCrossRateAsString", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateAsString")
    @ResponseWrapper(localName = "GetRealTimeCrossRateAsStringResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetRealTimeCrossRateAsStringResponse")
    @WebResult(name = "GetRealTimeCrossRateAsStringResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CrossRate getRealTimeCrossRateAsString(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String from,
        @WebParam(name = "To", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String to
    );

    /**
     * Returns the latest possible cross rate.
     */
    @WebMethod(operationName = "GetLatestCrossRates", action = "http://www.xignite.com/services/GetLatestCrossRates")
    @RequestWrapper(localName = "GetLatestCrossRates", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRates")
    @ResponseWrapper(localName = "GetLatestCrossRatesResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetLatestCrossRatesResponse")
    @WebResult(name = "GetLatestCrossRatesResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.ArrayOfCrossRate getLatestCrossRates(

        @WebParam(name = "From", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String from,
        @WebParam(name = "Tos", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String tos
    );

    /**
     * Draw a intraday currency chart for a time range in a binary format
     *             
     */
    @WebMethod(operationName = "GetCurrencyIntradayChartCustom", action = "http://www.xignite.com/services/GetCurrencyIntradayChartCustom")
    @RequestWrapper(localName = "GetCurrencyIntradayChartCustom", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustom")
    @ResponseWrapper(localName = "GetCurrencyIntradayChartCustomResponse", targetNamespace = "http://www.xignite.com/services/", className = "com.xignite.services.GetCurrencyIntradayChartCustomResponse")
    @WebResult(name = "GetCurrencyIntradayChartCustomResult", targetNamespace = "http://www.xignite.com/services/")
    public com.xignite.services.CurrencyChartIntraday getCurrencyIntradayChartCustom(

        @WebParam(name = "Symbol", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String symbol,
        @WebParam(name = "StartTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String endTime,
        @WebParam(name = "TimeZone", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String timeZone,
        @WebParam(name = "Style", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.StockChartStyles style,
        @WebParam(name = "Width", targetNamespace = "http://www.xignite.com/services/")
        int width,
        @WebParam(name = "Height", targetNamespace = "http://www.xignite.com/services/")
        int height,
        @WebParam(name = "PeriodType", targetNamespace = "http://www.xignite.com/services/")
        java.lang.String periodType,
        @WebParam(name = "TickPeriods", targetNamespace = "http://www.xignite.com/services/")
        int tickPeriods,
        @WebParam(name = "Design", targetNamespace = "http://www.xignite.com/services/")
        com.xignite.services.ChartDesign design
    );
}
